from __future__ import annotations

import inspect
import os
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from feishu.client import FeishuConfig, load_feishu_config
from tools.bitable_schema import BitableSchema, BitableSchemaError, clean_record_fields, load_bitable_schema
from tools.registry import ToolRegistry
from tools.spec import ToolSpec


READ_PREFIXES = (
    "get_",
    "list_",
    "search_",
    "parse_",
    "check_",
    "is_",
    "resolve_",
)
WRITE_WORDS = (
    "create",
    "update",
    "delete",
    "move",
    "copy",
    "send",
    "reply",
    "append",
    "add_",
    "remove",
    "batch_create",
    "batch_update",
)


@dataclass(frozen=True)
class AdapterToolInfo:
    legacy_name: str
    description: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    side_effect: bool



def _keywords(*values: str) -> list[str]:
    out: list[str] = []
    for value in values:
        raw = str(value or "").strip()
        if not raw:
            continue
        for part in [raw, raw.lower(), raw.replace("表", ""), raw.replace("清单", "")]:
            part = part.strip()
            if part and part not in out:
                out.append(part)
    return out


def _matches(text: str, keywords: list[str]) -> bool:
    low = str(text or "").lower()
    return any(k.lower() in low for k in keywords if k)


def _match_score(text: str, keywords: list[str]) -> int:
    low = str(text or "").lower()
    score = 0
    for idx, key in enumerate(keywords):
        k = key.lower()
        if not k:
            continue
        if low == k:
            score += 100 - idx
        elif k in low:
            score += 30 - min(idx, 20)
    return score


def _select_table(tables: list[dict[str, Any]], keywords: list[str]) -> dict[str, Any] | None:
    if not tables:
        return None
    scored = []
    for table in tables:
        score = _match_score(str(table.get("name") or ""), keywords)
        scored.append((score, table))
    scored.sort(key=lambda item: item[0], reverse=True)
    if scored and scored[0][0] > 0:
        return scored[0][1]
    return tables[0]


class FeishuToolAdapter:
    """Bridge all tools from the user's ``feishu_adapter`` package into the current ToolExecutor.

    The wrapped adapter remains application-token based by default. To keep the runtime app-tool-only,
    any ``user_access_token`` field generated by an LLM is stripped before invoking legacy tools.
    """

    def __init__(self, *, config: FeishuConfig | None = None, client: Any | None = None) -> None:
        self.config = config or load_feishu_config()
        self.client = client
        self._legacy_registry = None
        self._legacy_runtime = None
        self._legacy_event_bus = None
        self._tool_infos: dict[str, AdapterToolInfo] = {}
        self._inbound_handler: Callable[[dict[str, Any]], Any] | None = None
        self._pump_started = False
        self._pump_lock = threading.Lock()
        # The original adapter starts Feishu IM WebSocket from register() when this env is on.
        # Default it on so the adapter is actually wired when credentials and lark-oapi exist.
        os.environ.setdefault("FEISHU_ENABLE_IM_WS", "1")
        try:
            self.bitable_schema: BitableSchema | None = load_bitable_schema(app_token=self.config.bitable_app_token)
        except BitableSchemaError:
            self.bitable_schema = None
        self._load_legacy_adapter()

    @property
    def ready(self) -> bool:
        return bool(self.config.app_id and self.config.app_secret)

    @property
    def tool_infos(self) -> dict[str, AdapterToolInfo]:
        return dict(self._tool_infos)

    def bind_inbound_handler(self, handler: Callable[[dict[str, Any]], Any]) -> None:
        """Route legacy Feishu WS message events into the current runtime."""
        self._inbound_handler = handler
        self._ensure_event_pump()

    def register(self, registry: ToolRegistry) -> None:
        for name, info in sorted(self._tool_infos.items()):
            registry.register(
                ToolSpec(
                    name=name,
                    description=info.description,
                    args_schema=info.input_schema,
                    side_effect=info.side_effect,
                    handler=self._make_handler(name),
                    auth_type="app",
                )
            )
        self._register_common_aliases(registry)

    def _load_legacy_adapter(self) -> None:
        from tool_integration.events import EventBus
        from tool_integration.runtime import ToolRuntime
        from tool_integration.tools import ToolRegistry as LegacyToolRegistry

        import feishu_adapter.feishu_bitable as feishu_bitable
        import feishu_adapter.feishu_contact as feishu_contact
        import feishu_adapter.feishu_docx as feishu_docx
        import feishu_adapter.feishu_drive as feishu_drive
        import feishu_adapter.feishu_im_group as feishu_im_group
        import feishu_adapter.feishu_im_message as feishu_im_message
        import feishu_adapter.feishu_message_tools as feishu_message_tools
        import feishu_adapter.feishu_wiki as feishu_wiki

        self._legacy_event_bus = EventBus()
        self._legacy_event_bus.subscribe("current_runtime_bridge", ["*"])
        legacy_registry = LegacyToolRegistry()
        modules = [
            feishu_message_tools,
            feishu_contact,
            feishu_im_group,
            feishu_im_message,
            feishu_bitable,
            feishu_docx,
            feishu_drive,
            feishu_wiki,
        ]
        for module in modules:
            self._call_register(module, legacy_registry, self._legacy_event_bus)
        self._legacy_registry = legacy_registry
        self._legacy_runtime = ToolRuntime(legacy_registry, self._legacy_event_bus, config=dict(os.environ))
        self._tool_infos = {
            name: AdapterToolInfo(
                legacy_name=name,
                description=tool.spec.description,
                input_schema=self._app_only_schema(tool.spec.input_schema),
                output_schema=tool.spec.output_schema,
                side_effect=self._infer_side_effect(name),
            )
            for name, tool in legacy_registry.tools.items()
        }

    @staticmethod
    def _call_register(module: Any, registry: Any, event_bus: Any) -> None:
        fn = getattr(module, "register", None)
        if not callable(fn):
            return
        try:
            sig = inspect.signature(fn)
            if "event_bus" in sig.parameters:
                fn(registry, event_bus=event_bus)
            else:
                fn(registry)
        except TypeError:
            fn(registry)

    def _make_handler(self, legacy_name: str) -> Callable[[dict[str, Any]], dict[str, Any]]:
        def handler(args: dict[str, Any]) -> dict[str, Any]:
            if self._legacy_runtime is None:
                raise RuntimeError("legacy feishu_adapter runtime is not loaded")
            clean_args = self._app_only_args(args)
            result = self._legacy_runtime.invoke(legacy_name, clean_args)
            self._drain_legacy_events_once()
            if not result.get("ok"):
                raise RuntimeError(result.get("message") or result.get("error_type") or str(result))
            if "result" in result:
                return result["result"] if isinstance(result["result"], dict) else {"result": result["result"]}
            return result
        return handler

    def _register_common_aliases(self, registry: ToolRegistry) -> None:
        aliases: dict[str, tuple[str, str, dict[str, Any], Callable[[dict[str, Any]], dict[str, Any]]]] = {
            "feishu.contact.search_user": (
                "feishu_contact_resolve_user_in_department_tree",
                "应用身份在通讯录部门树中按姓名/邮箱/手机号/工号查找用户。",
                {"type": "object", "required": ["query"], "properties": {"query": {"type": "string"}, "department_id": {"type": "string"}, "user_id_type": {"type": "string"}, "max_matches": {"type": "integer"}}},
                lambda a: {"name": a.get("query", ""), "department_id": a.get("department_id", "0"), "user_id_type": a.get("user_id_type", "open_id"), "max_matches": a.get("max_matches", 5)},
            ),
            "feishu.im.create_chat": (
                "feishu_im_create_group_with_members",
                "应用身份创建包含指定成员的会话/群聊；用于拿到 chat_id 后继续发消息。",
                {"type": "object", "required": [], "properties": {"user_id": {"type": "string"}, "open_id": {"type": "string"}, "user_id_list": {"type": "array", "items": {"type": "string"}}, "name": {"type": "string"}, "description": {"type": "string"}, "user_id_type": {"type": "string"}}},
                self._alias_create_chat_args,
            ),
            "feishu.im.send_message": (
                "feishu_im_send_text_to_chat",
                "应用身份向 chat_id 发送文本消息。若要回复原消息，请使用 feishu.im.reply_message。",
                {"type": "object", "required": ["text"], "properties": {"receive_id": {"type": "string"}, "chat_id": {"type": "string"}, "text": {"type": "string"}, "uuid": {"type": "string"}}},
                lambda a: {"chat_id": a.get("chat_id") or a.get("receive_id"), "text": a.get("text", ""), "uuid": a.get("uuid")},
            ),
            "feishu.im.reply_message": (
                "feishu_im_reply_text",
                "应用身份回复指定飞书 message_id。",
                {"type": "object", "required": ["message_id", "text"], "properties": {"message_id": {"type": "string"}, "text": {"type": "string"}}},
                lambda a: {"message_id": a.get("message_id") or a.get("reply_to_message_id"), "text": a.get("text", "")},
            ),
            "feishu.bitable.create_record": (
                "feishu_bitable_create_record",
                "应用身份在多维表格中创建记录。",
                {"type": "object", "required": ["app_token", "table_id", "fields"], "properties": {"app_token": {"type": "string"}, "table_id": {"type": "string"}, "fields": {"type": "object"}}},
                lambda a: a,
            ),
            "feishu.bitable.list_records": (
                "feishu_bitable_search_records",
                "应用身份搜索/列出多维表格记录。",
                {"type": "object", "required": ["app_token", "table_id"], "properties": {"app_token": {"type": "string"}, "table_id": {"type": "string"}, "page_size": {"type": "integer"}, "filter": {"type": "string"}, "view_id": {"type": "string"}}},
                lambda a: a,
            ),
            "feishu.bitable.update_record": (
                "feishu_bitable_update_record",
                "应用身份更新多维表格记录。",
                {"type": "object", "required": ["app_token", "table_id", "record_id", "fields"], "properties": {"app_token": {"type": "string"}, "table_id": {"type": "string"}, "record_id": {"type": "string"}, "fields": {"type": "object"}}},
                lambda a: a,
            ),
            "feishu.bitable.batch_create_records": (
                "feishu_bitable_batch_create_records",
                "应用身份在多维表格中批量创建记录。",
                {"type": "object", "required": ["app_token", "table_id", "records"], "properties": {"app_token": {"type": "string"}, "table_id": {"type": "string"}, "records": {"type": "array", "items": {"type": "object"}}}},
                lambda a: a,
            ),
        }
        for alias, (legacy_name, description, schema, transform) in aliases.items():
            if registry.get(alias) is not None or legacy_name not in self._tool_infos:
                continue
            registry.register(
                ToolSpec(
                    name=alias,
                    description=description,
                    args_schema=schema,
                    side_effect=self._tool_infos[legacy_name].side_effect,
                    handler=self._make_alias_handler(legacy_name, transform),
                    auth_type="app",
                )
            )

        self._register_configured_bitable_tools(registry)


    def _register_configured_bitable_tools(self, registry: ToolRegistry) -> None:
        if self.bitable_schema is None:
            return
        schema_catalog = self.bitable_schema.llm_catalog()
        if registry.get("feishu.bitable.schema") is None:
            registry.register(
                ToolSpec(
                    name="feishu.bitable.schema",
                    description="读取当前应用配置好的多维表格 schema。不会搜索 app/table；表配置来自 config/bitable_schema.yaml，app_token 来自 FEISHU_BITABLE_APP_TOKEN 或 yaml 根节点。",
                    args_schema={"type": "object", "properties": {}},
                    side_effect=False,
                    handler=lambda args: schema_catalog,
                    auth_type="app",
                )
            )
        if registry.get("feishu.bitable.create_named_record") is None:
            registry.register(
                ToolSpec(
                    name="feishu.bitable.create_named_record",
                    description=(
                        "按配置表名创建一条多维表格记录。不要自己寻找 app_token/table_id；"
                        "传 table_key，例如 Risks/Projects/Tasks。字段必须使用 schema 中 write_allowed=true 的中文字段名。"
                    ),
                    args_schema={
                        "type": "object",
                        "required": ["table_key", "fields"],
                        "properties": {
                            "table_key": {"type": "string", "description": "配置表 key，例如 Risks。"},
                            "fields": {"type": "object"},
                            "strict": {"type": "boolean", "description": "默认 true；严格校验未知字段和禁止写入字段。"},
                        },
                    },
                    side_effect=True,
                    handler=self._create_named_record,
                    auth_type="app",
                )
            )
        if registry.get("feishu.bitable.batch_create_named_records") is None:
            registry.register(
                ToolSpec(
                    name="feishu.bitable.batch_create_named_records",
                    description=(
                        "按配置表名批量创建多维表格记录。不要自己寻找 app_token/table_id；"
                        "传 table_key，例如 Risks。records 每项可为 {fields:{...}} 或直接字段 object。"
                    ),
                    args_schema={
                        "type": "object",
                        "required": ["table_key", "records"],
                        "properties": {
                            "table_key": {"type": "string"},
                            "records": {"type": "array", "items": {"type": "object"}},
                            "strict": {"type": "boolean"},
                        },
                    },
                    side_effect=True,
                    handler=self._batch_create_named_records,
                    auth_type="app",
                )
            )

    def _create_named_record(self, args: dict[str, Any]) -> dict[str, Any]:
        if self.bitable_schema is None:
            raise RuntimeError("未加载多维表格 schema：请提供 config/bitable_schema.yaml 和 FEISHU_BITABLE_APP_TOKEN")
        table = self.bitable_schema.get_table(str(args.get("table_key") or ""))
        fields = clean_record_fields(table, args.get("fields") if isinstance(args.get("fields"), dict) else {}, strict=bool(args.get("strict", True)))
        return self._legacy_call_result("feishu_bitable_create_record", {
            "app_token": self.bitable_schema.app_token,
            "table_id": table.table_id,
            "fields": fields,
        })

    def _batch_create_named_records(self, args: dict[str, Any]) -> dict[str, Any]:
        if self.bitable_schema is None:
            raise RuntimeError("未加载多维表格 schema：请提供 config/bitable_schema.yaml 和 FEISHU_BITABLE_APP_TOKEN")
        table = self.bitable_schema.get_table(str(args.get("table_key") or ""))
        strict = bool(args.get("strict", True))
        raw_records = args.get("records") if isinstance(args.get("records"), list) else []
        if not raw_records:
            raise RuntimeError("records 不能为空")
        records: list[dict[str, Any]] = []
        for item in raw_records:
            if not isinstance(item, dict):
                raise RuntimeError("records 每项必须是 object")
            raw_fields = item.get("fields") if isinstance(item.get("fields"), dict) else item
            fields = clean_record_fields(table, raw_fields, strict=strict)
            records.append({"fields": fields})
        return self._legacy_call_result("feishu_bitable_batch_create_records", {
            "app_token": self.bitable_schema.app_token,
            "table_id": table.table_id,
            "records": records,
        })

    def _make_alias_handler(self, legacy_name: str, transform: Callable[[dict[str, Any]], dict[str, Any]]) -> Callable[[dict[str, Any]], dict[str, Any]]:
        legacy_handler = self._make_handler(legacy_name)
        def handler(args: dict[str, Any]) -> dict[str, Any]:
            return legacy_handler(transform(args))
        return handler

    def _legacy_call_result(self, legacy_name: str, args: dict[str, Any]) -> dict[str, Any]:
        if self._legacy_runtime is None:
            raise RuntimeError("legacy feishu_adapter runtime is not loaded")
        result = self._legacy_runtime.invoke(legacy_name, self._app_only_args(args))
        self._drain_legacy_events_once()
        if not result.get("ok"):
            raise RuntimeError(result.get("message") or result.get("error_type") or str(result))
        payload = result.get("result")
        return payload if isinstance(payload, dict) else {"result": payload}

    def _find_bitable_table(self, args: dict[str, Any]) -> dict[str, Any]:
        query = str(args.get("query") or "风险").strip()
        table_query = str(args.get("table_query") or query or "风险表").strip()
        space_query = str(args.get("space_query") or "").strip()
        max_spaces = max(1, min(int(args.get("max_spaces") or 20), 50))
        max_depth = max(0, min(int(args.get("max_depth") or 2), 4))
        page_size = max(1, min(int(args.get("page_size") or 50), 100))
        keywords = _keywords(query, table_query, "风险", "风险表", "风险清单", "risk")
        table_keywords = _keywords(table_query, query, "风险", "风险表", "风险清单", "risk")

        candidates: list[dict[str, Any]] = []
        spaces_page = self._legacy_call_result("feishu_wiki_list_spaces", {"page_size": max_spaces})
        spaces = spaces_page.get("items") if isinstance(spaces_page.get("items"), list) else []
        for space in spaces:
            if not isinstance(space, dict):
                continue
            space_id = str(space.get("space_id") or "")
            space_name = str(space.get("name") or "")
            if not space_id:
                continue
            if space_query and not _matches(space_name, [space_query]):
                continue
            queue: list[tuple[str, int]] = [("", 0)]
            while queue:
                parent, depth = queue.pop(0)
                nodes_page = self._legacy_call_result(
                    "feishu_wiki_list_nodes",
                    {"space_id": space_id, "parent_node_token": parent, "page_size": page_size},
                )
                nodes = nodes_page.get("items") if isinstance(nodes_page.get("items"), list) else []
                for node in nodes:
                    if not isinstance(node, dict):
                        continue
                    title = str(node.get("title") or "")
                    obj_type = str(node.get("obj_type") or "")
                    obj_token = str(node.get("obj_token") or "")
                    node_token = str(node.get("node_token") or "")
                    if obj_type == "bitable" and obj_token:
                        score = _match_score(title, keywords)
                        candidates.append({
                            "score": score,
                            "app_token": obj_token,
                            "app_title": title,
                            "space_id": space_id,
                            "space_name": space_name,
                            "node_token": node_token,
                        })
                    if depth < max_depth and node.get("has_child") and node_token:
                        queue.append((node_token, depth + 1))

        candidates.sort(key=lambda item: int(item.get("score") or 0), reverse=True)
        tried: list[dict[str, Any]] = []
        for candidate in candidates:
            app_token = str(candidate.get("app_token") or "")
            if not app_token:
                continue
            tables_page = self._legacy_call_result("feishu_bitable_list_tables", {"app_token": app_token, "page_size": page_size})
            tables = tables_page.get("items") if isinstance(tables_page.get("items"), list) else []
            normalized_tables = [table for table in tables if isinstance(table, dict)]
            table = _select_table(normalized_tables, table_keywords)
            tried.append({"app_token": app_token, "app_title": candidate.get("app_title"), "tables": normalized_tables[:10]})
            if table:
                return {
                    "app_token": app_token,
                    "table_id": str(table.get("table_id") or ""),
                    "table_name": str(table.get("name") or ""),
                    "app_title": str(candidate.get("app_title") or ""),
                    "space_id": str(candidate.get("space_id") or ""),
                    "space_name": str(candidate.get("space_name") or ""),
                    "node_token": str(candidate.get("node_token") or ""),
                    "matched_by": "wiki_bitable_node_and_table_name",
                    "candidates": candidates[:10],
                }
        raise RuntimeError(f"没有找到匹配的风险多维表格：query={query}, table_query={table_query}, tried={tried[:5]}")

    @staticmethod
    def _alias_create_chat_args(args: dict[str, Any]) -> dict[str, Any]:
        users = args.get("user_id_list") if isinstance(args.get("user_id_list"), list) else []
        one = args.get("user_id") or args.get("open_id")
        if one and not users:
            users = [one]
        return {
            "user_id_list": users,
            "name": args.get("name") or "应用私聊",
            "description": args.get("description") or "由应用工具创建",
            "user_id_type": args.get("user_id_type") or ("open_id" if args.get("open_id") and not args.get("user_id") else "user_id"),
        }

    @staticmethod
    def _app_only_schema(schema: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(schema, dict):
            return {"type": "object", "properties": {}}
        clean = dict(schema)
        props = dict(clean.get("properties") or {})
        props.pop("user_access_token", None)
        clean["properties"] = props
        required = clean.get("required")
        if isinstance(required, list):
            clean["required"] = [x for x in required if x != "user_access_token"]
        return clean

    @staticmethod
    def _app_only_args(args: dict[str, Any]) -> dict[str, Any]:
        clean = dict(args or {})
        clean.pop("user_access_token", None)
        return clean

    @staticmethod
    def _infer_side_effect(name: str) -> bool:
        raw = name.lower().replace("-", "_").replace(".", "_")
        tail = raw
        for prefix in ("feishu_",):
            if tail.startswith(prefix):
                tail = tail[len(prefix):]
        if any(word in tail for word in WRITE_WORDS):
            return True
        if any(tail.startswith(prefix) or f"_{prefix}" in tail for prefix in READ_PREFIXES):
            return False
        return True

    def _ensure_event_pump(self) -> None:
        if self._legacy_event_bus is None:
            return
        with self._pump_lock:
            if self._pump_started:
                return
            self._pump_started = True
        threading.Thread(target=self._event_pump_loop, daemon=True, name="feishu-adapter-event-pump").start()

    def _event_pump_loop(self) -> None:
        while True:
            try:
                self._drain_legacy_events_once()
            except Exception:
                pass
            time.sleep(0.2)

    def _drain_legacy_events_once(self) -> None:
        if self._legacy_event_bus is None:
            return
        events = self._legacy_event_bus.drain("current_runtime_bridge")
        for ev in events:
            event_type = str(getattr(ev, "event_type", ""))
            payload = getattr(ev, "payload", {}) or {}
            if event_type == "feishu.im.message.received" and self._inbound_handler:
                raw = payload.get("raw") if isinstance(payload, dict) else None
                if isinstance(raw, dict):
                    self._inbound_handler(raw)
