class FeishuAdaptorError(RuntimeError): ...
class FeishuAuthError(FeishuAdaptorError): ...
class FeishuNotConfiguredError(FeishuAdaptorError): ...
class BaseTableNotFoundError(FeishuAdaptorError): ...
class BaseFieldValidationError(FeishuAdaptorError): ...
